Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -22,4 +22,12 @@ jobs:
         run: npm install -g jslint # Installer JSLint globalement
 
       - name: Run JSLint
-        run: jslint *.js # Remplacez `your_file.js` par le nom de votre fichier JavaScript que vous voulez lint
+        run: |
+          jslint your_file.js || exit 1 # Exécuter JSLint et sortir avec le code 1 s'il y a des erreurs
+
+      - name: Verify linting results
+        run: exit 0 # Cette étape est uniquement pour clarifier que la vérification s'est terminée avec succès
+
+      - name: Stop workflow if errors were found
+        if: ${{ failure() }}
+        run: echo "JSLint found errors. Cancelling the workflow." && exit 1
